name: Continuous Architecture CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "artifact/**"
      - ".github/workflows/**"

  push:
    branches:
      - main
    paths:
      - "artifact/**"
      - ".github/workflows/**"

jobs:
  execute_rules:
    name: Validar cumplimiento
    uses: ContinuousArchitecture/ContinuousArchitectureWorkflow/.github/workflows/compliance.yml@main
