name: Continuous Architecture CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "artifact/**"
      - ".github/workflows/**"

  push:
    branches:
      - main
    paths:
      - "artifact/**"
      - ".github/workflows/**"

jobs:
  execute_rules:
    name: Validar cumplimiento
    uses: fad3dc07-e43b-4db5-92bd-fbfecbc5ae1b/ContinuousArchitectureWorkflow/.github/workflows/compliance.yml@main
